"""
Planning models for the OpenMetaMind swarm.

This module defines the data structures for task decomposition and execution planning.
"""

from typing import List, Optional
from pydantic import BaseModel, Field


class Subtask(BaseModel):
    """
    A unit of work to be executed by a specific agent.
    
    The Planner decomposes user tasks into subtasks with dependencies.
    """
    subtask_id: str = Field(description="Unique identifier for this subtask")
    agent_id: str = Field(description="ID of the agent that should execute this subtask")
    task_description: str = Field(description="Natural language description of the task")
    required_inputs: List[str] = Field(
        default_factory=list,
        description="Keys from blackboard needed as inputs (e.g., ['table_list'])"
    )
    produces_output: str = Field(
        description="Key that will be written to blackboard upon completion (e.g., 'quality_reports')"
    )
    dependencies: List[str] = Field(
        default_factory=list,
        description="List of subtask_ids that must complete before this subtask can start"
    )
    max_retries: int = Field(default=2, description="Maximum number of retry attempts")
    timeout_seconds: int = Field(default=60, description="Timeout in seconds for execution")


class ExecutionPlan(BaseModel):
    """
    The execution plan generated by the Planner.
    
    Contains subtasks with dependencies for sequential execution via the Supervisor pattern.
    """
    subtasks: List[Subtask] = Field(description="All subtasks in the plan")
    estimated_duration: str = Field(description="Human-readable estimate (e.g., '45.2s')")
    # Note: parallel_groups removed - agents execute sequentially via Supervisor pattern
    # Use dependencies field in Subtask to define ordering instead
    
    def get_subtask(self, subtask_id: str) -> Optional[Subtask]:
        """Get a subtask by its ID."""
        for subtask in self.subtasks:
            if subtask.subtask_id == subtask_id:
                return subtask
        return None